spring:
  application:
    name: api-gateway
  config:
    import: "optional:configserver:http://localhost:8088" # Optional meaning start application without config server

application:
  security:
    jwt:
      secret-key: ${application.security.jwt.secret-key}

gateway:
  excludedUrl: ${gateway.excludedUrl}