spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lowerCaseServiceId: true
      routes:
        - id: auth-service
          uri: lb://auth-service
          predicates:
            - Path=/api/v1/user/**
        - id: portfolio-service
          uri: lb://portfolio-service
          predicates:
            - Path=/api/v1/portfolio/**
          filters:
            - AuthenticationPreFilter  # Ensure this filter is correctly configured
      default-filters:
        - PreserveHostHeader
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins:
              - "http://localhost:3000"  # Accept request from the frontend at port 3000
            allowedMethods:
              - GET
              - POST
              - DELETE
              - PUT
              - PATCH
            allowedHeaders:
              - Content-Type
              - responseType
              - Authorization
              - X-User-Roles  # ✅ Explicitly allow custom headers
              - username
            allowCredentials: true

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: ${EUREKA_SERVER_URL:http://localhost:8761/eureka}
  instance:
    hostname: api-gateway

server:
  port: 4000

gateway:
  excludedUrl: /api/v1/user/login, /api/v1/user/register

application:
  security:
    jwt:
      secret-key: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
