spring:
  datasource:
    url: jdbc:mysql://localhost:3306/micro-portfolio
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
  redis:
    host: localhost  # Redis is running on Docker but accessible on the host
    port: 6379       # Default Redis port
    timeout: 6000ms  # Optional connection timeout
    lettuce:
      pool:
        max-active: 8
        max-idle: 8
        min-idle: 2
logging:
  level:
    org:
      springframework:
        security: DEBUG

server:
  port: 8081
  servlet:
    context-path: /api/v1/portfolio

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: ${EUREKA_SERVER_URL:http://localhost:8761/eureka}
  instance:
    hostname: portfolio-service
    prefer-ip-address: true

management:
  tracing:
    sampling:
      probability: 1.0

application:
  security:
    jwt:
      secret-key: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
      expiration: 86400000